# Generated by Django 3.0.4 on 2020-04-11 06:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=100)),
                ('issuer_designation', models.CharField(choices=[('M', 'Minister'), ('C', 'Commissioner'), ('P', 'Police Officer')], default='P', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('P', 'Permanent'), ('O', 'OneTime'), ('T', 'Temporary')], default='O', max_length=2)),
                ('pass_username', models.CharField(blank=True, max_length=250)),
                ('pass_user_phonenumber', models.IntegerField(max_length=10)),
                ('pass_user_aadhar_number', models.IntegerField(max_length=12)),
                ('pass_issued_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pass_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pass_end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pass_vehicle', models.CharField(blank=True, max_length=25)),
                ('pass_people_count', models.IntegerField(max_length=100)),
                ('pass_state_validity', models.CharField(choices=[('TN', 'Tamil Nadu'), ('KE', 'Kerala'), ('AP', 'Andhra Pradesh'), ('KA', 'Karnataka'), ('TE', 'Telangana'), ('NIL', 'Nil')], default='NIL', max_length=3)),
                ('pass_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('W', 'Withheld'), ('R', 'Rejected')], default='P', max_length=2)),
                ('pass_medical_verification', models.CharField(choices=[('Y', 'required'), ('N', 'notrequired')], default='N', max_length=2)),
                ('pass_description', models.CharField(max_length=20000)),
                ('pass_user_pic', models.ImageField(blank=True, upload_to='')),
                ('pass_qr_pic', models.ImageField(blank=True, upload_to='')),
                ('pass_issuer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passsystem.Issuer')),
            ],
        ),
    ]
