# Generated by Django 3.0.4 on 2020-04-20 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=1000)),
                ('address_streetline1', models.CharField(max_length=1000)),
                ('address_streetline2', models.CharField(max_length=1000)),
                ('address_streetline3', models.CharField(max_length=1000)),
                ('address_country', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_zipcode', models.CharField(max_length=10)),
                ('address_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('organisation_primaryuser', models.CharField(max_length=500)),
                ('organisation_name', models.CharField(max_length=1000)),
                ('organisation_address', models.IntegerField()),
                ('organisation_phonenumber', models.CharField(max_length=10, unique=True)),
                ('organisation_altphonenumber', models.CharField(blank=True, max_length=10)),
                ('organisation_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation_createdon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roles_rolename', models.IntegerField(choices=[(0, 'Citizen'), (1, 'Admin'), (2, 'Issuer'), (3, 'Scanner')], primary_key=True, serialize=False)),
                ('roles_roledescription', models.CharField(max_length=10000)),
                ('roles_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('roles_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='passsystem.Team')),
                ('team_organisationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_organisationid', to='passsystem.Organisation')),
                ('team_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_role', to='passsystem.Roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(blank=True, max_length=100)),
                ('user_middlename', models.CharField(blank=True, max_length=100)),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2)),
                ('user_image', models.ImageField(blank=True, default='', upload_to='')),
                ('user_phonenumber', models.CharField(max_length=10, unique=True)),
                ('user_altphonenumber', models.CharField(blank=True, max_length=10)),
                ('user_addressid', models.IntegerField()),
                ('user_identity', models.IntegerField()),
                ('user_teamid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teamid', to='passsystem.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_vehiclenumber', models.CharField(max_length=50, unique=True)),
                ('vehicle_vehicletype', models.CharField(max_length=100)),
                ('vehicle_orgid', models.IntegerField(blank=True)),
                ('vehicle_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle_createdby', to='passsystem.User')),
                ('vehicle_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle_uid', to='passsystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('pass_passtype', models.CharField(choices=[('P', 'Permanent'), ('O', 'OneTime'), ('T', 'Temporary')], default='O', max_length=2)),
                ('pass_passreason', models.CharField(max_length=20000)),
                ('pass_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('pass_expirydate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pass_validitystate', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Expired'), (3, 'Revoked')], default=0)),
                ('pass_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('pass_zipcode', models.CharField(max_length=10)),
                ('pass_radius', models.CharField(max_length=1000)),
                ('pass_medicalverification', models.CharField(choices=[('Y', 'required'), ('N', 'notrequired')], default='N', max_length=2)),
                ('pass_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pass_createdby', to='passsystem.User')),
                ('pass_issuedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pass_issuedby', to='passsystem.User')),
                ('pass_issuedto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pass_issuedto', to='passsystem.User')),
                ('pass_updatedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pass_updaedby', to='passsystem.User')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('identity_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_idtype', models.IntegerField(choices=[(0, 'AadharID'), (1, 'Driving License'), (2, 'PanCard Number')])),
                ('identity_idnumber', models.CharField(max_length=100)),
                ('identity_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_updateson', models.DateTimeField(default=django.utils.timezone.now)),
                ('identity_createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_identity_createdby', to='passsystem.User')),
                ('identity_updatedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_identity_updatedby', to='passsystem.User')),
            ],
        ),
    ]
