# Generated by Django 3.0.4 on 2020-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='roles_passread',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='roles_passwrite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='roles_teamread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='roles_teamwrite',
            field=models.BooleanField(default=False),
        ),
    ]
