# Generated by Django 3.0.4 on 2020-04-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passsystem', '0002_auto_20200424_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_teamid',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
