# Generated by Django 3.0.4 on 2020-04-24 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('passsystem', '0003_auto_20200424_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.Group')),
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='passsystem.Team')),
                ('team_organisationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_organisationid', to='passsystem.Organisation')),
                ('team_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_role', to='passsystem.Roles')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.group', models.Model),
        ),
        migrations.AddField(
            model_name='user',
            name='user_teamid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teamid', to='passsystem.Team'),
        ),
    ]
