# Generated by Django 3.0.4 on 2020-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passsystem', '0003_auto_20200413_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='organisation_altphonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_altphonenumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
