# Generated by Django 3.0.4 on 2020-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passsystem', '0004_auto_20200424_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_addressid',
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_city',
            field=models.CharField(default='Coimbatore', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_name',
            field=models.CharField(default='DoorOrHouseNumber', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_streetline1',
            field=models.CharField(default='Addressline1', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_streetline2',
            field=models.CharField(default='Addressline2', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_streetline3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address_zipcode',
            field=models.CharField(default='641001', max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_address',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='roles',
            name='roles_passread',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_identity',
            field=models.IntegerField(blank=True),
        ),
    ]
